### ISSUE TITLE
Can't separate any song

### ISSUE THREAD

**Issue by WiseMatthack** [thooore/SpleeterGUI#1]
When extracting the files from the release to the original location where I installed SpleeterGUI, the programs says that there is no input argument, as shown in the image here
![image](https://user-images.githubusercontent.com/32242507/116933453-db8b2080-ac63-11eb-941f-d349c8f85034.png)

**Comment by thooore** [comment]
I believe you are using an older version of the core Spleeter software, you should be able to update it to the latest version by clicking the "spleeter core upgrade" button under the help menu. They introduced some breaking changes with Spleeter 2.1.0, but this program should work with any later version!

![image](https://user-images.githubusercontent.com/69172033/119114973-f365f100-ba26-11eb-93f1-3276ec1d7f3b.png)
